server:
  port: 3001
  servlet:
    context-path: /api

app:
  base-url: http://localhost:3001/api/
file:
  upload-dir: uploads/

spring:
  application:
    name: chatop
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:${APP_DB_PORT}/${APP_DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
  default-produces-media-type: application/json


application:
  security:
    jwt:
      secret-key: eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxNzc5MzEyMSwiaWF0IjoxNzE3NzkzMTIxfQAGwpFGfUBPeiFfh0EINuUodLQqQpulmJvnFsoGSMf34
      expiration: 3600000 # 1000 * 60 * 60

logging:
  level:
    com:
      openclassrooms:
        chatpo: DEBUG
